# Shell variables
# Generated by 'wal'
wallpaper='/home/martin/.config/wpg/wallpapers/synthwave-background-5.jpg'

# Special
background='#1a1019'
foreground='#ffdffc'
cursor='#ffdffc'

# Colors
color0='#1a1019'
color1='#953360'
color2='#6B658D'
color3='#E4B328'
color4='#A0526E'
color5='#63526A'
color6='#CB5C52'
color7='#c9a9bf'
color8='#392237'
color9='#ce357b'
color10='#8073c6'
color11='#fff122'
color12='#df5a8a'
color13='#855e95'
color14='#ff6858'
color15='#ffdffc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
