--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/martin/.config/wpg/wallpapers/synthwave-background-5.jpg"

-- Special
background="#1a1019"
foreground="#ffdffc"
cursor="#ffdffc"

-- Colors
color0="#1a1019"
color1="#953360"
color2="#6B658D"
color3="#E4B328"
color4="#A0526E"
color5="#63526A"
color6="#CB5C52"
color7="#c9a9bf"
color8="#392237"
color9="#ce357b"
color10="#8073c6"
color11="#fff122"
color12="#df5a8a"
color13="#855e95"
color14="#ff6858"
color15="#ffdffc"
